Laboratory work #2, Maria Manukhina - 23FPL1
fipl-hse/2024-2-level-labs pull request #110
Opened 2024-10-18 08:21 UTC by MariaManukhina

2024-10-22 12:44 UTC, Vasilisa-Blyudova commented
Unfortunately, I don't see any progress in your PR. It's time to start implementing Laboratory work #2.

2024-10-28 16:43 UTC, Vasilisa-Blyudova reviewed
Good work! Try to implement the laboratory work on 6

2024-10-28 16:43 UTC, Vasilisa-Blyudova commented on lab_2_retrieval_w_bm25/main.py
> +    my_text.split()
there is already `split` in the loop on line 26

2024-10-28 16:43 UTC, Vasilisa-Blyudova commented on lab_2_retrieval_w_bm25/main.py
> +    my_text = text.lower()
try to use `lower` in loop before `split`

2024-10-30 15:36 UTC, MariaManukhina commented
If I add right formula, which is in file, pycharm says unexpected character after line continuation character. If I changed \ to /, it says invalid syntax.

2024-11-18 20:31 UTC, Vasilisa-Blyudova commented on .github/workflows/ci_pipeline.yml
> +    timeout-minutes: 11
revert

2024-11-20 18:53 UTC, artyomtugaryov requested changes

2024-11-20 18:53 UTC, artyomtugaryov commented on .github/workflows/ci_pipeline.yml
> +    timeout-minutes: 11
Amazing move! Agree with Vasilisa Mikhailovna

2024-11-20 18:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    return tokenized_text
add a new empty line after the function

2024-11-20 18:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    n_t = document_tokens.count
I do not believe that it works

2024-11-20 18:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    calc_tf_idf = tf / idf
so not create the variable

2024-11-20 18:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/start.py
> +    return None
remove

2024-11-20 18:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/start.py
> +#    result = None
looks like it will rise AssertionError

2024-11-21 13:55 UTC, closed without merging