Laboratory work #3, Olga Kostina - 23FPL2
fipl-hse/2024-2-level-labs pull request #141
Opened 2024-11-08 08:25 UTC by olyakostii1na

2024-11-12 19:02 UTC, Vasilisa-Blyudova requested changes

2024-11-12 19:02 UTC, Vasilisa-Blyudova commented on lab_3_ann_retriever/main.py
> +            document_without_stopwords = self._remove_stop_words(tokenized_document)
do you really need to use `_remove_stop_words` method?

2024-11-12 19:02 UTC, Vasilisa-Blyudova commented on lab_3_ann_retriever/main.py
> +                clear_text.append(token)
try to use list comprehension

2024-11-18 18:48 UTC, Vasilisa-Blyudova commented
No progress since last review

2024-11-20 19:06 UTC, artyomtugaryov requested changes
No new changes

2024-11-22 17:40 UTC, closed without merging