Laboratory work #3, Maxim Krivenko - 23FPL2
fipl-hse/2024-2-level-labs pull request #145
Opened 2024-11-10 17:23 UTC by makskrivenko

2024-11-12 04:54 UTC, artyomtugaryov requested changes
Nothing to review. Hope I see your amazing code soon!

2024-11-18 18:19 UTC, artyomtugaryov requested changes

2024-11-18 18:19 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> -    tokenized_list = []
? Revert!

2024-11-18 18:19 UTC, artyomtugaryov commented on lab_3_ann_retriever/settings.json
> +    "target_score": 4
Try 6

2024-11-20 18:37 UTC, artyomtugaryov requested changes

2024-11-20 18:37 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +
revert

2024-11-20 18:37 UTC, artyomtugaryov commented on lab_3_ann_retriever/start.py
> +    print(result)
why?

2024-11-21 21:36 UTC, makskrivenko commented on lab_3_ann_retriever/main.py
> +
done

2024-11-22 17:41 UTC, closed without merging