Laboratory work #3, Valeria Bogdanova - 23FPL1
fipl-hse/2024-2-level-labs pull request #152
Opened 2024-11-14 16:53 UTC by lerabogdanova

2024-11-18 15:06 UTC, artyomtugaryov requested changes
Is it really for 6? If so, try for 8

2024-11-18 15:06 UTC, artyomtugaryov commented on 2024-2-level-labs
How did you do this? Revert this change!

2024-11-18 15:06 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        return Tokenizer._remove_stop_words(self, tokens)
```suggestion
        return self._remove_stop_words(tokens)
```

2024-11-18 15:06 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +            tok_documents.append(Tokenizer.tokenize(self, doc))
the same

2024-11-19 14:10 UTC, lerabogdanova commented on lab_3_ann_retriever/main.py
> +            tok_documents.append(Tokenizer.tokenize(self, doc))
Done

2024-11-19 14:11 UTC, lerabogdanova commented on lab_3_ann_retriever/main.py
> +        return Tokenizer._remove_stop_words(self, tokens)
Done

2024-11-20 14:45 UTC, artyomtugaryov requested changes

2024-11-20 14:45 UTC, artyomtugaryov commented on 2024-2-level-labs
What is it? revert

2024-11-20 14:45 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        else:
remove `else`

2024-11-20 14:45 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        tok_documents = []
list comprehension

2024-11-20 15:28 UTC, lerabogdanova commented on lab_3_ann_retriever/main.py
> +        else:
Done

2024-11-22 17:45 UTC, closed without merging