Laboratory work #3, Ivan Shmakov - 23FPL1.
fipl-hse/2024-2-level-labs pull request #162
Opened 2024-11-19 10:37 UTC by CloudWhisp

2024-11-20 19:16 UTC, artyomtugaryov requested changes

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        text = self._remove_stop_words(text.split())
do not create the variable

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        tokens_cleared = [elem for elem in tokens if elem not in self._stop_words]
.

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        vector = self._calculate_tf_idf(tokenized_document)
.

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        docs = sorted(docs, key= lambda x:x[1])
.

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        vector = self._vectorizer.vectorize(tokenized_text)
.

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        self.payload = payload
add empty line

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/main.py
> +        self._root = None
add empty line

2024-11-20 19:16 UTC, artyomtugaryov commented on lab_3_ann_retriever/start.py
> +    #knn_retriever = BasicSearchEngine(vectorizer=vectorizer, tokenizer=tokenizer)
remove

2024-11-21 04:43 UTC, CloudWhisp commented on lab_3_ann_retriever/main.py
> +        vector = self._calculate_tf_idf(tokenized_document)
Done

2024-11-21 04:45 UTC, CloudWhisp commented on lab_3_ann_retriever/main.py
> +        vector = self._vectorizer.vectorize(tokenized_text)
Done

2024-11-21 04:46 UTC, CloudWhisp commented on lab_3_ann_retriever/main.py
> +        self._root = None
Fixed

2024-11-21 07:34 UTC, CloudWhisp commented on lab_3_ann_retriever/start.py
> +    #knn_retriever = BasicSearchEngine(vectorizer=vectorizer, tokenizer=tokenizer)
Done

2024-11-22 17:48 UTC, closed without merging