ok
fipl-hse/2024-2-level-labs pull request #18
Opened 2024-09-06 11:27 UTC by makskrivenko

2024-09-24 14:14 UTC, artyomtugaryov requested changes

2024-09-24 14:14 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    if isinstance(text, str):
`if not` -> return `None` 
Return bad values as soon as possible.

2024-09-24 14:14 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +            if i.isalpha() and i != "º":
Do we really need this special check?

2024-09-24 14:14 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        for i in tokens:
try `any` or `all`

2024-09-24 14:14 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    if isinstance(language, str) and isinstance(text, str):
the same - return None as soon as possible

2024-09-24 14:14 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/start.py
> +    Launches an i mplementation
return

2024-09-24 14:14 UTC, artyomtugaryov commented on seminars/__init__.py
> +print("something")
Hello, I do not want to see it the next time

2024-09-25 17:29 UTC, makskrivenko commented on lab_1_classify_by_unigrams/main.py
> +        for i in tokens:
Вместо всей конструкции?

2024-09-30 12:59 UTC, artyomtugaryov requested changes
every, EVERY code inside function must be AFTER docstring

2024-09-30 12:59 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/__init__.py
> +s = "name"
revert

2024-09-30 12:59 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
`else` is unnecessary

2024-09-30 12:59 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
`unnecessary`

2024-10-02 12:33 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +            freq_dict[letter] = tokens.count(letter) / len(tokens)
You calculate the same value many times for similar symbols. Can you optimize it and calculate it only for unique

2024-10-02 12:33 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    mse = num_sum / len(actual)
do not create the variable - return `as is`

2024-10-02 12:34 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    comparison = calculate_mse(unknown_lst, compare_lst)
the same - do not create the variale

2024-10-02 12:34 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        language = profile_2['name']
return

2024-10-02 12:34 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        language = profile_1['name']
return

2024-10-02 12:34 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        language = equal_lst[0]
return

2024-10-02 12:34 UTC, artyomtugaryov commented on seminars/practice_3_lists.py
> +
revert

2024-10-05 19:50 UTC, closed without merging