Laboratory work #4, Semenova Taisiya - 23FPL2
fipl-hse/2024-2-level-labs pull request #188
Opened 2024-11-28 13:53 UTC by semtassta

2024-12-03 16:03 UTC, artyomtugaryov requested changes
Looks strange. Did you pass the 3rd lab?

2024-12-03 17:16 UTC, semtassta commented
> Looks strange. Did you pass the 3rd lab?

Not yet

2024-12-09 16:38 UTC, artyomtugaryov requested changes

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                    raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-09 16:38 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-11 06:21 UTC, artyomtugaryov requested changes

2024-12-11 06:21 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +from lab_2_retrieval_w_bm25.main import calculate_bm25
All imports together

2024-12-11 06:21 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +        super().__init__(self._corpus)
super should be the first line in this method

2024-12-11 06:21 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-11 06:21 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Add message

2024-12-11 06:21 UTC, artyomtugaryov commented on lab_4_retrieval_w_clustering/main.py
> +        return self.__clusters
Are you sure that you need to create new  clustrs in `self.__clusters`? Probably you need create it in another variable and return

2024-12-11 09:41 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:41 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:41 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:41 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:42 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:44 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +        super().__init__(self._corpus)
done

2024-12-11 09:45 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +from lab_2_retrieval_w_bm25.main import calculate_bm25
done

2024-12-11 09:57 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:57 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                    raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +                raise ValueError
Done

2024-12-11 09:58 UTC, semtassta commented on lab_4_retrieval_w_clustering/main.py
> +            raise ValueError
Done

2024-12-14 10:34 UTC, closed without merging