Внесены первые изменения в рамках лабораторной работы
fipl-hse/2024-2-level-labs pull request #35
Opened 2024-09-08 07:11 UTC by minabdeyeva

2024-09-24 11:49 UTC, artyomtugaryov requested changes

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    numbers = '0123456789'
Can you store all "bad symbols" together? in one variable

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        else:
``else` is unnecessary cause you use `continue`

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    if tozenized_text == []:
bad condition. Use just `not tozenized_text`

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    if tokens is None or type(tokens) is not list:
`type(...) is not ...` should be replaced with `isinstance`

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        if type(token) is not str:
The same - `isinstance`

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        elif token in frequencies:
try to simplify - set 0 if `token not in frequencies` and do +1 always

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    if type(language) is not str or language not in ['en', 'de'] or type(text) is not str:
THe same

2024-09-24 11:49 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
``else` is unnecessary cause you did `return`

2024-09-28 21:01 UTC, minabdeyeva commented
done

2024-09-30 09:42 UTC, artyomtugaryov requested changes
What about 10? I`m sure you can!

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +        low_symb = symb.lower()
let use `symb.lower()` only once for the source big string?

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
`else` is unnecessary

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    profile = {}
You can avoid creating the vatiable by using `return {'name': ..., ...}`

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    for i in range(n):
use `enumerate`

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    n = len(predicted)
I believe you don't need the variable

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    def sort_by_alpha(lang1, lang2):
No! Please, do not create functions inside functions!

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    else:
`else` is unnecessary

2024-09-30 09:42 UTC, artyomtugaryov commented on seminars/practice_3_lists.py
> +    counter = 0
revert the file.

2024-09-30 09:42 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/settings.json
> +  "target_score": 8
👎🏻

2024-09-30 15:19 UTC, minabdeyeva commented on lab_1_classify_by_unigrams/settings.json
> +  "target_score": 8
done

2024-10-02 13:54 UTC, artyomtugaryov submitted a review, later dismissed

2024-10-05 19:56 UTC, closed without merging