Laboratory work #1, Veronika Tsytsulina - 23FPL1
fipl-hse/2024-2-level-labs pull request #40
Opened 2024-09-08 19:37 UTC by VeronicaTs30

2024-09-30 11:28 UTC, artyomtugaryov requested changes
What about 6?

2024-09-30 11:28 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +
revert

2024-09-30 11:28 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +    for elem in set(tokens):
Perfect

2024-09-30 11:28 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/start.py
> +from main import tokenize
add an empty line

2024-09-30 11:28 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/start.py
> +
revert

2024-09-30 15:57 UTC, VeronicaTs30 commented on lab_1_classify_by_unigrams/start.py
> +from main import tokenize
done

2024-09-30 15:59 UTC, VeronicaTs30 commented on lab_1_classify_by_unigrams/main.py
> +
done

2024-09-30 16:11 UTC, VeronicaTs30 commented on lab_1_classify_by_unigrams/main.py
> +a = 13
done

2024-09-30 16:12 UTC, VeronicaTs30 commented on lab_1_classify_by_unigrams/main.py
> +    for elem in set(tokens):
done

2024-10-02 12:59 UTC, artyomtugaryov submitted a review, later dismissed
What about 8?

2024-10-05 19:57 UTC, closed without merging