Laboratory work #1 Nazhmutdinova Polina-23FPL1
fipl-hse/2024-2-level-labs pull request #63
Opened 2024-09-26 20:04 UTC by Palina-frog-dog-whatelse

2024-09-30 10:04 UTC, artyomtugaryov requested changes
Looks like nothing to review. I hope you will be in time

2024-09-30 10:04 UTC, artyomtugaryov commented on lab_1_classify_by_unigrams/main.py
> +print("hello world")
revert

2024-10-02 13:32 UTC, artyomtugaryov commented
Nothing to review

2024-10-08 14:02 UTC, artyomtugaryov requested changes
Nothing to review again

2024-10-22 12:52 UTC, artyomtugaryov requested changes
THere is not any update

2024-10-28 14:38 UTC, artyomtugaryov requested changes
No new changes

2024-10-30 16:09 UTC, artyomtugaryov requested changes
Address previous comments

2024-11-05 17:54 UTC, artyomtugaryov requested changes
The same comments

2024-11-12 18:18 UTC, artyomtugaryov requested changes
Nothing new to review

2024-11-18 18:23 UTC, artyomtugaryov requested changes
Nothing new

2024-11-20 18:31 UTC, artyomtugaryov requested changes
Nothing to review again

2024-11-26 17:54 UTC, artyomtugaryov commented
Nothing to review

2024-12-03 16:59 UTC, artyomtugaryov requested changes
Nothing to review

2024-12-09 16:56 UTC, artyomtugaryov requested changes
Nothing new to review

2024-12-12 13:25 UTC, Palina-frog-dog-whatelse commented on lab_1_classify_by_unigrams/main.py
> +print("hello world")
Как мне сделать revert?

2024-12-17 10:06 UTC, closed without merging