Laboratory work #2, Tasya Kakoulina - 23FPL2
fipl-hse/2024-2-level-labs pull request #79
Opened 2024-10-07 11:12 UTC by tasya-kakoulina

2024-10-08 14:18 UTC, artyomtugaryov requested changes
Perfect

2024-10-08 14:18 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +        word += token
join is better

2024-10-08 14:18 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    return tokens if tokens else None
`tokens or None`

2024-10-08 14:18 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    return bm_dict if bm_dict else None
.

2024-10-08 14:18 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    return res if res else None
.

2024-10-08 16:09 UTC, tasya-kakoulina commented on lab_2_retrieval_w_bm25/main.py
> +        word += token
done

2024-10-08 16:09 UTC, tasya-kakoulina commented on lab_2_retrieval_w_bm25/main.py
> +    return tokens if tokens else None
done

2024-10-08 16:09 UTC, tasya-kakoulina commented on lab_2_retrieval_w_bm25/main.py
> +    return bm_dict if bm_dict else None
done

2024-10-15 15:50 UTC, artyomtugaryov requested changes

2024-10-17 18:29 UTC, tasya-kakoulina commented on lab_2_retrieval_w_bm25/main.py
> +    return [token for token in tokens if token not in stopwords] or None
didn't get it :( should i use sorted here? or in rank_documents? but why?..

2024-10-17 18:29 UTC, tasya-kakoulina commented on lab_2_retrieval_w_bm25/main.py
> +    vocab = set(sum(documents, []))
me too!

2024-11-02 18:28 UTC, closed without merging