Laboratory work #2, Amina Abdeyeva - 23FPL1
fipl-hse/2024-2-level-labs pull request #90
Opened 2024-10-08 19:53 UTC by minabdeyeva

2024-10-15 15:58 UTC, artyomtugaryov requested changes

2024-10-15 15:58 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    for word in stopwords:
use `any`

2024-10-15 15:58 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    else:
you do not need `else`

2024-10-15 15:58 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    # remove_stopwords(['there', 'was', 'a', 'boy', 'named, 'henry'], ['was', 'named'])
rm

2024-10-22 11:48 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    # divide by spaces - ['the', 'first%', 'sentence><.', 'the', 'sec&*ond', 'sent@ence', '#.']
remove

2024-10-22 11:48 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    for word in text_by_space:
interesting implementation, but too dificult

2024-10-28 14:59 UTC, minabdeyeva commented
changes are made, mistakes fixed

2024-10-28 15:01 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if map_IDF_scores:
.

2024-10-28 15:02 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if map_scores:
the same

2024-10-29 21:24 UTC, minabdeyeva commented
done

2024-10-30 14:41 UTC, minabdeyeva commented on lab_2_retrieval_w_bm25/main.py
> +    if map_scores:
fixed

2024-10-30 16:46 UTC, artyomtugaryov requested changes

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +        tokens = []
looks strange, please fine more elegant way

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    return clean_tokens
try to return `clean_tokens or None`

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if frequency:
the same

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if map_idf_scores:
the same

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if map_scores:
no

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if not bm5_doc:
the same

2024-10-30 16:46 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    if not sorted_ranking_map:
the same

2024-10-30 21:25 UTC, minabdeyeva commented
done and fixed

2024-11-02 18:36 UTC, closed without merging