Laboratory work #2, Aleksandra Doroshina - 23FPL1
fipl-hse/2024-2-level-labs pull request #93
Opened 2024-10-10 17:42 UTC by DoroshinaAleksandra

2024-10-15 16:00 UTC, artyomtugaryov requested changes

2024-10-15 16:00 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    tokenized_text = tokenized_text_str.split()
do not create the variable

2024-10-15 16:00 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/settings.json
> +    "target_score": 6
what about 8?

2024-10-15 19:36 UTC, DoroshinaAleksandra commented on lab_2_retrieval_w_bm25/main.py
> +    tokenized_text = tokenized_text_str.split()
done

2024-10-22 11:47 UTC, artyomtugaryov requested changes

2024-10-22 11:47 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +            if word not in unique_words:
use set

2024-10-22 11:47 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +        for word in text:
convert text to set without loop

2024-10-28 06:59 UTC, DoroshinaAleksandra commented on lab_2_retrieval_w_bm25/main.py
> +            if word not in unique_words:
done

2024-10-28 06:59 UTC, DoroshinaAleksandra commented on lab_2_retrieval_w_bm25/main.py
> +        for word in text:
done

2024-10-28 15:03 UTC, artyomtugaryov requested changes

2024-10-30 16:53 UTC, artyomtugaryov requested changes

2024-10-30 16:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +            tokenized_text += element
`continue` and remove `else`

2024-10-30 16:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/main.py
> +    for token in tokens:
Please find a new way without copy and remove

2024-10-30 16:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/start.py
> +            return None
remove `None`, just `return`

2024-10-30 16:53 UTC, artyomtugaryov commented on lab_2_retrieval_w_bm25/start.py
> +    return None
remove

2024-11-02 18:37 UTC, closed without merging